data_path                     :  /home/s/data/cear/indoor/mocap2_well-lit_trot

# RealSense camera parameters
rs_width                      : 640
rs_height                     : 480
rs_depth_scale                : 0.001
rs_fps                        : 60
rs_rgb_k: [381.0546264648438, 380.6285705566406, 316.6095581054688, 248.536376953125] # new
rs_rgb_d: [-0.058237917721271515, 0.0692759975790977, 0.000362122984370217, -0.000120137752674054, -0.0220816992223263]
rs_depth_k: [382.7142944335938, 382.7142944335938, 316.7781372070312, 241.8565368652344] # new and good
rs_depth_d: [0, 0, 0, 0, 0]
rs_depth_to_rgb: [-0.0013899849, 0.0024341078, -0.0010085609, 0.99999556, -0.059056371, 0.00020030836, 0.00059907947]
rs_rgb_to_davis_event: [-0.000657167076182, 0.0267250808646, 0.00549935517768, 0.999627478252, 0.019354, -0.048871, -0.06149] # xyzw xyz 346 new
rs_robot_to_rgb: [0.5, -0.5, 0.5, 0.5, -0.012, 0.132, -0.1] # xyzw xyz
imu_to_marker: [0.4939908159, 0.5004118135, -0.4961898151, 0.5092708102, -0.017683758, -0.0195426, -0.00486914] # xyzw xyz

# DVX event camera parameters
event_template_half_size      : 21
dvx346_width                  : 346
dvx346_height                 : 260
dvx346_k: [246.21513879135846, 245.61468896582758, 157.8584677903505, 123.18704548605702] # new
dvx346_d: [-0.3623771631103021, 0.10756855063552792, 0.001994420333408483, 0.007012245326386505, 0]

dvxplorer_lite_width                  : 320
dvxplorer_lite_height                 : 240
dvxplorer_lite_k: [270.02944359462646, 267.85844044621354, 142.0589965458161, 116.29740759541482]
dvxplorer_lite_d: [-0.39334604502583076, 0.17215752932640968, 0.00045589492638387243, -0.0007602650238944599, 0.0]